Fix/ci
* fix: ci

* fix: ci

* fix: ci

* fix: ci

* fix: ci

* fix: ci

* fix: ci

* fix: ci

* fix: ci

* fix: ci

* fix: ci

* fix: ci

* fix: ci

* fix: ci

* fix: ci

* fix: ci

* fix: ci

* fix: ci

* fix: ci

* fix: ci

* fix: ci

* fix: ci

* fix: ci

* fix: ci

* fix: ci

* fix: ci

diff --git a/.github/workflows/pol.yml b/.github/workflows/pol.yml
--- a/.github/workflows/pol.yml
+++ b/.github/workflows/pol.yml
@@ -2,6 +2,8 @@ name: pol
 
 on:
   push:
+    branches:
+      - master
 
 env:
   BACK_EXEC: "pol-back"
@@ -11,38 +13,43 @@ jobs:
     runs-on: ubuntu-22.04
     container:
       image: golang:1.22.5
+    defaults:
+      run:
+        working-directory: backend
     steps:
+      - uses: actions/checkout@v4
       - uses: actions/setup-go@v5
+        with:
+            go-version: 1.22.5
       - name: build project
         run: |
-          cd backend
-          go mod download
-          go build -o $BACK_EXEC
+          go get .
+          go build -o $BACK_EXEC -buildvcs=false
           if [[ ! -f $BACK_EXEC ]]; then
-            echo "::error title=This executable was not found $BACK_EXEC::"
-            exit 1
+          echo "::error title=This executable was not found $BACK_EXEC::"
+          exit 1
           fi
-  pol-front-build:
+  pol-front:
     needs: pol-back-build
     runs-on: ubuntu-22.04
-    container:
-      image: oven/bun:1
+    defaults:
+      run:
+        working-directory: frontend
     steps:
-      - uses: actions/checkout@v3
-      - name: build project front
-        run: |
-          cd frontend
-          bun install
-          bun run build
-  pol-front-cypress-tests:
-    needs: pol-front-
-    runs-on: ubuntu-22.04
-    container:
-      image: oven/bun:1
-    steps:
+      - uses: actions/checkout@v4
+      - uses: actions/setup-node@v4
+        with:
+          node-version: 21.6.2
+      - name: install dependencies
+        run: yarn install
+      - name: Build project
+        run: yarn build
       - uses: cypress-io/github-action@v6
-      - name: test project front using cypress
+        with:
+          working-directory: frontend
+          build: yarn build
+          start: yarn preview
+          wait-on-timeout: 300
+      - name: Run cypress tests
         run: |
-          cd frontend
-          bun install
-          bun run cy:run
+          yarn cy:run
